using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;

namespace BRClib.Scripts
{
    using Env = Environment;

    public static class Shelf
    {
        const string PyGetProjInfo = "get_project_info.py";
        const string PyMixdownAudio = "mixdown_audio.py";
        static readonly string AppDataDir = 
            Path.Combine(Env.GetFolderPath(Env.SpecialFolder.ApplicationData), "BlenderRenderController");

        private static Dictionary<PyScript, ScriptPaths> _internalData =
            new Dictionary<PyScript, ScriptPaths>
            {
                [PyScript.GetProjectInfo] = ScriptPaths.Empty,
                [PyScript.MixdownAudio] = ScriptPaths.Empty
            };


        public static string GetProjectInfo
        {
            get
            {
                return GetScriptPath(PyScript.GetProjectInfo);
            }
            set
            {
                SetCustomScriptPath(PyScript.GetProjectInfo, value);
            }
        }

        public static string MixdownAudio
        {
            get
            {
                return GetScriptPath(PyScript.MixdownAudio);
            }
            set
            {
                SetCustomScriptPath(PyScript.MixdownAudio, value);
            }
        }

        public static string EmbeddedScriptToDisk(PyScript script, string dir = null)
        {
            var rsName = GetPyScriptFileName(script);
            return EmbeddedScriptToDisk(rsName, dir);
        }


        public enum PyScript
        {
            GetProjectInfo,
            MixdownAudio
        }


        private static void SetCustomScriptPath(PyScript script, string newPath)
        {
            var sp = _internalData[script];
            sp.Custom = newPath;
            _internalData[script] = sp;
        }


        private static string GetScriptPath(PyScript script)
        {
            var path = GetCustomPath(script) ?? GetDefaultPath(script, false);
            return path;
        }

        private static string GetDefaultPath(PyScript script, bool allowNull)
        {
            var sp = _internalData[script];

            if (sp.Default == null && !allowNull)
            {
                sp.Default = EmbeddedScriptToDisk(script);
            }

            _internalData[script] = sp;

            return sp.Default;
        }

        private static string GetCustomPath(PyScript script)
        {
            var custom = _internalData[script].Custom;
            return File.Exists(custom) ? custom : null;
        }

        private static string EmbeddedScriptToDisk(string resourceName, string dir = null)
        {
            var assembly = Assembly.GetExecutingAssembly();
            var resPath = assembly.GetName().Name + ".Scripts." + resourceName;

            if (dir == null)
            {
                dir = Path.Combine(AppDataDir, "scripts");
                Directory.CreateDirectory(dir);
            }

            var file = Path.Combine(dir, resourceName);

            if (CheckVerFile() && File.Exists(file))
            {
                return file;
            }

            using (var resStream = assembly.GetManifestResourceStream(resPath))
            using (var fileStream = File.Create(file))
            {
                string genHeader = "# Generated by BRClib, do not modify!\n";
                byte[] header = Encoding.UTF8.GetBytes(genHeader);

                fileStream.Write(header, 0, header.Length);

                // copy contents to file
                resStream.Seek(0, SeekOrigin.Begin);
                resStream.CopyTo(fileStream);
            }

            return file;
        }

        private static bool CheckVerFile()
        {
            var brc_ver = Env.GetEnvironmentVariable("BRC_VER");

            var verFile = Path.Combine(AppDataDir, "ver");

            if (!File.Exists(verFile))
            {
                File.WriteAllText(verFile, brc_ver);
                return false;
            }

            var savedVer = File.ReadAllText(verFile);

            if (savedVer == brc_ver)
            {
                return true;
            }

            File.WriteAllText(verFile, brc_ver);
            return false;
        }


        private static string GetPyScriptFileName(PyScript script)
        {
            switch (script)
            {
                case PyScript.GetProjectInfo:
                    return PyGetProjInfo;
                case PyScript.MixdownAudio:
                    return PyMixdownAudio;
                default:
                    return null;
            }
        }


        struct ScriptPaths
        {
            public string Default;
            public string Custom;

            public static ScriptPaths Empty
            {
                get
                {
                    ScriptPaths sp;
                    sp.Default = null;
                    sp.Custom = null;

                    return sp;
                }
            }

            public override bool Equals(object obj)
            {
                if (obj == null || GetType() != obj.GetType())
                {
                    return false;
                }

                var sp = (ScriptPaths)obj;

                return this.Equals(sp);
            }

            public bool Equals(ScriptPaths sp)
            {
                return Default == sp.Default
                    && Custom == sp.Custom;
            }

            public override int GetHashCode()
            {
                return base.GetHashCode();
            }
        }

    }
}
